name: check-contrib

on: [push, pull_request]  # would you need to define PRs containing .eb files?

permissions:
  contents: read  # to fetch code (actions/checkout)

jobs:
  check-contrib:
    name: Run EasyBuild check-contrib
    runs-on: ubuntu-22.04

    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python env
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install EasyBuild and pycodestyle  # needed for check-contrib
        run: pip install easybuild==4.9.4 pycodestyle

      - name: Run check-contrib
        run: |
          for file in $(find . -name '*.eb'); do
            echo "Checking $file"
            eb "$file" --check-contrib
          done
